### ISSUE TITLE
testes falham se não estiver autenticado

### ISSUE THREAD

**Issue by marcio0** [marcio0/django-piston#1]
```
======================================================================
ERROR: test_post_failure_to_a_given_id (rest.tests.HandlersTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mcruz/teste/sgonzales/netvision/rest/tests.py", line 269, in test_post_failure_to_a_given_id
    content_type='application/json', follow=True)
  File "/home/mcruz/teste/env/lib/python2.7/site-packages/Django-1.3.1-py2.7.egg/django/test/client.py", line 449, in post
    response = super(Client, self).post(path, data=data, content_type=content_type, **extra)
  File "/home/mcruz/teste/env/lib/python2.7/site-packages/Django-1.3.1-py2.7.egg/django/test/client.py", line 259, in post
    return self.request(**r)
  File "/home/mcruz/teste/env/lib/python2.7/site-packages/Django-1.3.1-py2.7.egg/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/mcruz/teste/env/lib/python2.7/site-packages/Django-1.3.1-py2.7.egg/django/views/decorators/vary.py", line 22, in inner_func
    response = func(*args, **kwargs)
  File "/home/mcruz/teste/django-piston/piston/resource.py", line 130, in __call__
    return actor(request)
TypeError: challenge() takes exactly 1 argument (2 given)

----------------------------------------------------------------------
```

Os testes falham ao invés de retornar 403

**Comment by marcio0** [comment]
Acontece no netvision devido a mudança feita em e189d3c094f0d91c03b70fc9c899d80e4192a8d4.
